language: java

install: true

jdk:
  - oraclejdk8

script:
  - ./gradlew uberJar
  
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: "./build/libs/taxprinter-1.0-SNAPSHOT-all.jar"
  skip_cleanup: true
  on:
    tags: true
